# Generated by Django 3.1.1 on 2020-10-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Added_JOBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Nature', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default=1, max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('discription', models.TextField(max_length=3500)),
                ('Published_on', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField()),
                ('imag', models.ImageField(default='logo_defuel.png', upload_to='imags/')),
                ('Salary', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-Published_on'],
            },
        ),
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=211)),
            ],
        ),
        migrations.CreateModel(
            name='City_sity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country_cont')),
            ],
        ),
        migrations.CreateModel(
            name='CEVEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=102)),
                ('Email', models.EmailField(max_length=300)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='cvs/')),
                ('Coverletter', models.TextField(max_length=3500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('job_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_home.added_jobs')),
            ],
        ),
        migrations.AddField(
            model_name='added_jobs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_home.cartegory'),
        ),
        migrations.AddField(
            model_name='added_jobs',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_home.city_sity'),
        ),
    ]
