# Generated by Django 3.1.1 on 2020-10-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('job_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='added_jobs',
            name='city',
        ),
        migrations.AddField(
            model_name='added_jobs',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country_cont'),
        ),
        migrations.DeleteModel(
            name='City_sity',
        ),
    ]
