# Generated by Django 3.1.1 on 2020-10-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201006_1810'),
        ('job_home', '0002_auto_20201006_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added_jobs',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country_cont'),
        ),
    ]
